name: Upload to Azure Blob Storage

on:
  push:
    branches:
      - main  # Trigger the workflow on every push to the main branch

jobs:
  upload:
    runs-on: ubuntu-latest  # Runs on the latest Ubuntu virtual machine

    steps:
      # 1️⃣ Checkout - Fetch the repository content from GitHub
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Login to Azure using the service principal credentials stored in GitHub Secrets
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # 3️⃣ Upload files from the `my-app` folder to the Azure Blob Storage container
      - name: Upload files to Azure Blob Storage
        run: |
          az storage blob upload-batch \
            --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT }} \
            --destination ${{ secrets.AZURE_STORAGE_CONTAINER }} \
            --source my-app \
            --auth-mode login
