name: Automate Blob Uploads

# on:
#   push:
#     branches:
#       - main  # Runs on push to main

permissions:
  contents: read   # Allows reading the repository contents

jobs:
  upload:
    runs-on: ubuntu-latest  # Runs on the latest Ubuntu virtual machine

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Login to Azure using Service Principal and Client Secret
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: '{"clientId": "${{ secrets.AZURE_CLIENT_ID }}", "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}", "tenantId": "${{ secrets.AZURE_TENANT_ID }}", "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}"}'

      # Upload files to Azure Blob Storage. --auth-mode login → Uses the currently logged-in Azure credentials to authenticate
      - name: Upload files to Azure Blob Storage
        run: |
          az storage blob upload-batch \
            --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT }} \
            --destination ${{ secrets.AZURE_STORAGE_CONTAINER }} \
            --source my-app \
            --auth-mode login