name: Managing Blob Storage

on:
  workflow_dispatch:
    inputs:
      update:
        description: 'Upload'
        required: false
        default: false
        type: boolean
      delete:
        description: 'Delete'
        required: false
        default: false
        type: boolean

permissions:
  contents: read  # Allows reading the repository contents

jobs:
  manage-blobs:
    runs-on: ubuntu-latest  # Runs on the latest Ubuntu virtual machine

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Login to Azure using Service Principal and Client Secret
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: '{"clientId": "${{ secrets.AZURE_CLIENT_ID }}", "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}", "tenantId": "${{ secrets.AZURE_TENANT_ID }}", "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}"}'
          # ✅ Use creds to pass the service principal credentials

      # 3️⃣ Upload files if 'update' is checked ✅
      - name: Upload files to Azure Blob Storage
        if: inputs.update == true
        run: |
          az storage blob upload-batch \
            --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT }} \
            --destination ${{ secrets.AZURE_STORAGE_CONTAINER }} \
            --source my-app \
            --auth-mode login  # Use AAD authentication instead of account key
        env:
          AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
          AZURE_STORAGE_CONTAINER: ${{ secrets.AZURE_STORAGE_CONTAINER }}

      # 4️⃣ Delete all blobs if 'delete' is checked ✅
      - name: Delete all files from Azure Blob Storage
        if: inputs.delete == true
        run: |
          az storage blob delete-batch \
            --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT }} \
            --source ${{ secrets.AZURE_STORAGE_CONTAINER }} \
            --auth-mode login
        env:
          AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
          AZURE_STORAGE_CONTAINER: ${{ secrets.AZURE_STORAGE_CONTAINER }}
